# Generated by Django 4.0.2 on 2022-06-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_perfor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roleid',
        ),
    ]
