# Generated by Django 4.0.2 on 2022-06-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_perfor', '0002_remove_user_roleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roleid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server_perfor.role'),
        ),
    ]
